[workspace]
authors = ["wtclarke <william.clarke@ndcn.ox.ac.uk>"]
channels = ["https://fsl.fmrib.ox.ac.uk/fsldownloads/fslconda/public/", "conda-forge"]
name = "special_issue_fmrs"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]
_configure_r_dev = {cmd = ['R', '-e', 'devtools::install_github("martin3141/spant", ref = "devel", dependencies = TRUE)']}
_simulate_data = {cmd = "Rscript data_generation/01_bednarik_simulation.R"}
generate_data = {cmd = "python data_generation/touch_up_data.py", depends-on = ["_simulate_data"]}

file-tree = {cmd = ['file-tree', 'dynamic_fitting.tree']}
first_level = {cmd = ['python', 'run_dynamic_fitting.py']}

[dependencies]
fsl_mrs = ">=2.4.10,<3"
ipykernel = ">=7.1.0,<8"
nilearn = ">=0.12.1,<0.13"
fsl-flameo = ">=2111.2,<2112"
r-devtools = ">=2.4.6,<3"
r = ">=4.5,<4.6"
r-nloptr = ">=2.2.1,<3"
r-lme4 = ">=1.1_37,<2"
file-tree = ">=1.6.0,<2"
fsl-pipe = ">=1.3.0,<2"
textual = ">=6.6.0,<7"
